name: Main
on:
  #  - push
  - pull_request
jobs:
  test:
    name: Test and Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run format
      - run: npm run test
